# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: netVlad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='netVlad.proto',
  package='netVlad',
  syntax='proto3',
  serialized_pb=_b('\n\rnetVlad.proto\x12\x07netVlad\"*\n\nNetRequest\x12\x0f\n\x07netType\x18\x01 \x01(\t\x12\x0b\n\x03img\x18\x02 \x01(\x0c\"(\n\x0bNetResponse\x12\x0c\n\x04\x66lag\x18\x01 \x01(\t\x12\x0b\n\x03vec\x18\x02 \x03(\x02\x32\x44\n\nNetConnect\x12\x36\n\x07img2vec\x12\x13.netVlad.NetRequest\x1a\x14.netVlad.NetResponse\"\x00\x42\x34\n\x18io.grpc.examples.netVladB\x0cNetVladProtoP\x01\xa2\x02\x07sendImgb\x06proto3')
)




_NETREQUEST = _descriptor.Descriptor(
  name='NetRequest',
  full_name='netVlad.NetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='netType', full_name='netVlad.NetRequest.netType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='img', full_name='netVlad.NetRequest.img', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=68,
)


_NETRESPONSE = _descriptor.Descriptor(
  name='NetResponse',
  full_name='netVlad.NetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='netVlad.NetResponse.flag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vec', full_name='netVlad.NetResponse.vec', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['NetRequest'] = _NETREQUEST
DESCRIPTOR.message_types_by_name['NetResponse'] = _NETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetRequest = _reflection.GeneratedProtocolMessageType('NetRequest', (_message.Message,), dict(
  DESCRIPTOR = _NETREQUEST,
  __module__ = 'netVlad_pb2'
  # @@protoc_insertion_point(class_scope:netVlad.NetRequest)
  ))
_sym_db.RegisterMessage(NetRequest)

NetResponse = _reflection.GeneratedProtocolMessageType('NetResponse', (_message.Message,), dict(
  DESCRIPTOR = _NETRESPONSE,
  __module__ = 'netVlad_pb2'
  # @@protoc_insertion_point(class_scope:netVlad.NetResponse)
  ))
_sym_db.RegisterMessage(NetResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030io.grpc.examples.netVladB\014NetVladProtoP\001\242\002\007sendImg'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class NetConnectStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.img2vec = channel.unary_unary(
          '/netVlad.NetConnect/img2vec',
          request_serializer=NetRequest.SerializeToString,
          response_deserializer=NetResponse.FromString,
          )


  class NetConnectServicer(object):
    """The greeting service definition.
    """

    def img2vec(self, request, context):
      """Sends a greeting
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_NetConnectServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'img2vec': grpc.unary_unary_rpc_method_handler(
            servicer.img2vec,
            request_deserializer=NetRequest.FromString,
            response_serializer=NetResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'netVlad.NetConnect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaNetConnectServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def img2vec(self, request, context):
      """Sends a greeting
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaNetConnectStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def img2vec(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting
      """
      raise NotImplementedError()
    img2vec.future = None


  def beta_create_NetConnect_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('netVlad.NetConnect', 'img2vec'): NetRequest.FromString,
    }
    response_serializers = {
      ('netVlad.NetConnect', 'img2vec'): NetResponse.SerializeToString,
    }
    method_implementations = {
      ('netVlad.NetConnect', 'img2vec'): face_utilities.unary_unary_inline(servicer.img2vec),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_NetConnect_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('netVlad.NetConnect', 'img2vec'): NetRequest.SerializeToString,
    }
    response_deserializers = {
      ('netVlad.NetConnect', 'img2vec'): NetResponse.FromString,
    }
    cardinalities = {
      'img2vec': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'netVlad.NetConnect', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
